import sweatpantImage from "@/assets/images/sweatpant.webp";
import turtleneckImage from "@/assets/images/turtleneck.webp";
import denimImage from "@/assets/images/denim.webp";
import blackcollegeImage from "@/assets/images/blackcollege.webp";
import militaryImage from "@/assets/images/military.webp";

export default [
  {
    id: 1,
    category: "Hoodie",
    name: "Heavy Fleece Sw",
    price: "Rp 3.130.000",
    like: 12,
    size: "M",
    imageLink: sweatpantImage,
    condition: "Very Good",
    color: "White",
  },
  {
    id: 2,
    category: "Hoodie",
    name: "Heavy Fleece Turtle Neck",
    price: "Rp 4.000.000",
    like: "40",
    size: "S",
    imageLink: turtleneckImage,
    condition: "Normal",
    color: "Cream",
  },
  {
    id: 3,
    category: "Hoodie",
    name: "The North Face High Pile Nuptse Puffer Jacket",
    price: "Rp 2.650.000",
    like: "20",
    size: "L",
    imageLink: denimImage,
    condition: "Normal",
    color: "Brown",
  },
  {
    id: 4,
    category: "Hoodie",
    name: " Black College Thing Tee",
    price: "Rp 3.000.000",
    like: "90",
    size: "S",
    imageLink: blackcollegeImage,
    condition: "Normal",
    color: "Cream",
  },
  {
    id: 5,
    category: "Hoodie",
    name: "Military Nylon Overshirt",
    price: "Rp 3.238.000",
    like: "10",
    size: "M",
    imageLink: militaryImage,
    condition: "Normal",
    color: "Green",
  },
  {
    id: 5,
    category: "Hoodie",
    name: "Military Nylon Overshirt",
    price: "Rp 3.238.000",
    like: "10",
    size: "M",
    imageLink: militaryImage,
    condition: "Normal",
    color: "Green",
  },
  {
    id: 5,
    category: "Hoodie",
    name: "Military Nylon Overshirt",
    price: "Rp 3.238.000",
    like: "10",
    size: "M",
    imageLink: militaryImage,
    condition: "Normal",
    color: "Green",
  },
  {
    id: 5,
    category: "Hoodie",
    name: "Military Nylon Overshirt",
    price: "Rp 3.238.000",
    like: "10",
    size: "M",
    imageLink: militaryImage,
    condition: "Normal",
    color: "Green",
  },
  {
    id: 5,
    category: "Hoodie",
    name: "Military Nylon Overshirt",
    price: "Rp 3.238.000",
    like: "10",
    size: "M",
    imageLink: militaryImage,
    condition: "Normal",
    color: "Green",
  },
  {
    id: 5,
    category: "Hoodie",
    name: "Military Nylon Overshirt",
    price: "Rp 3.238.000",
    like: "10",
    size: "M",
    imageLink: militaryImage,
    condition: "Normal",
    color: "Green",
  },
];
